mongo-addr: localhost:27017
api-addr: :8081
auth-username: admin
auth-password: password
location: 'http://localhost:8081'
private-key: 8PjzjakvIlh3BVFKe8axinRDutF6EDIfjtuf4+JaNow=
public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
access-log: access.log
