name: idm
version: git
summary: Identity Manager.
description: |
  Identity Manager.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  idm:
    command: bin/idserver -resource-path ${SNAP} -logging-config INFO ${SNAP_COMMON}/config.yaml
    daemon: simple
    plugs:
     - network
     - network-bind
  admin:
    command: bin/user-admin
    plugs:
     - home
     - network

parts:
  blues-identity:
    plugin: godeps
    source: ../..
    source-type: git
    go-importpath: github.com/CanonicalLtd/blues-identity
  static:
    plugin: dump
    source: ../..
    prime:
      - templates
